### ISSUE TITLE
Question - modules in smard

### ISSUE THREAD

**Issue by JTPfi** [vsevolodnedora/energy_market_analysis#1]
Dear Vsevolod

nice report and package! I was looking for a way to download data from smard and had some trouble - when I came across your report.

There's one question that bothers me: Where did you get the module IDs from smard? I saw them in your code but could not find them anywhere in the documentation of smard.

Cheers
Tobias

**Comment by vsevolodnedora** [comment]
Hello Tobias, 

I appreciate your interest in the project! Downloading data from SMARD is indeed tricky as there are limits and formats that I do not fully understand that can give an empty json. Thus, I implemented an iterative procedure where I progressively increased the amount of data I requested until the required number of entries in the json was found. This is not ideal, but it works. 

Regarding module_id. Some time ago, I stumbled upon this repo:
https://github.com/shroominic/smard-api 
There, the author shows how to call SMARD API for different data types. Additional trading IDs I found somewhere else. Sadly, I do not know if there is a place where each of the modules is clearly defiled and explained, even in the source repo of the Python API. 
 
 Please let me know if you have any further questions. 
 
 With warm regards, 
 Vsevolod Nedora

**Comment by JTPfi** [comment]
thanks!
